### ISSUE TITLE
Docker container failed error

### ISSUE THREAD

**Issue by Kakashi1499** [demisto/content#19123] opened 2022-05-20 11:03 UTC
Script failed to run: Docker code runner got container error: [Docker code script is in inconsistent state, expected pong but didn't got any response, exit error: Container exit with error. container name: [demistoserver_pyexec-ae9cdf1d-d970-4ef4-8684-35dd857a395c-demistopython33.9.8.24399--83] error: [exit status 1] stderr: [/usr/local/bin/python: can't find '__main__' module in '/tmp/pyrunner/_script_docker_python_loop.py'
] (2619) (2610)] (2611) (2603)

Above error displayed in export to demisto integration...

**Comment by DeanArbel** [comment] 2022-05-22 06:35
@Kakashi1499 Please open a ticket, this issue is not a bug, but related to your specific use case. Someone will get back 
to you and will assist you.

I'm closing the issue.

**Closed by DeanArbel** 2022-05-22 06:35 UTC
Labels: good first issue
